### ISSUE TITLE
evaluation time question

### ISSUE THREAD

**Issue by fengwei0907** [uzh-rpg/ssms_event_cameras#4]
Hello! I have been interested in RVT for a long time . I think you have done a great job! I have a question and I hope you can help me answer it. After I reproduce RVT, I have the following reasoning time:
Loading and preparing results DONE (t=0.41s) creating index Index created!
Running per image evaluation Evaluate annotation type * bbox * DONE (t=7.23s)
Accumulating evaluation results DONE (t=2.31s)
May I ask how to infer the time velocity in ms, just like 7.81 ms in your paper on the gen1 dataset.
I am using a 3090TIGPU with a batch_size of 1, so what should be the speed in ms?

**Comment by NikolaZubic** [comment]
Dear @fengwei0907 sorry for not answering before, I am very busy.

I guess this is already answered [here](https://github.com/uzh-rpg/RVT/issues/47).

Regarding your [question](https://github.com/uzh-rpg/ssms_event_cameras/issues/3#issuecomment-2080376417) about precision, unfortunately for now it only works at 32 precision, if you put it to 16 becomes less expressive. As you know associative scan is still now implemented in PyTorch, from what I have heard it will be soon, so this was more like a hack. Literally copying JAX core associative_scan code and using Torch functions.

**Comment by fengwei0907** [comment]
> Dear @fengwei0907 sorry for not answering before, I am very busy.
> 
> I guess this is already answered [here](https://github.com/uzh-rpg/RVT/issues/47).
> 
> Regarding your [question](https://github.com/uzh-rpg/ssms_event_cameras/issues/3#issuecomment-2080376417) about precision, unfortunately for now it only works at 32 precision, if you put it to 16 becomes less expressive. As you know associative scan is still not implemented in PyTorch, from what I have heard it will be soon, so this was more like a hack. Literally copying JAX's core associative_scan code and using Torch functions.

It's okay, my bro. Thank you for your reply, I will always keep an eye on your work.
