### ISSUE TITLE
Questions about the train time 

### ISSUE THREAD

**Issue by XavierZXY** [uzh-rpg/ssms_event_cameras#6]
Hi @NikolaZubic ,
Thanks for your wonderful job in event cameras.

Recently, I have been trying to replicate your work. I have installed the corresponding PyTorch and other libraries according to your readme file. However, with four 4090s, the training speed on the dataset gen1 is only 0.8 it/s. Is this speed normal?
What is the training speed on an A100?

Following is my train script.
```shell
#!/bin/bash
DATA_DIR="/home/data/gen1"
MDL_CFG=small
GPU_IDS=[0,1,2,3]
BATCH_SIZE_PER_GPU=4
TRAIN_WORKERS_PER_GPU=8
EVAL_WORKERS_PER_GPU=4
python RVT/train.py model=rnndet dataset=gen1 dataset.path=${DATA_DIR} wandb.project_name=ssms_event_cameras \
wandb.group_name=gen1 +experiment/gen1="${MDL_CFG}.yaml" hardware.gpus=${GPU_IDS} \
batch_size.train=${BATCH_SIZE_PER_GPU} batch_size.eval=${BATCH_SIZE_PER_GPU} \
hardware.num_workers.train=${TRAIN_WORKERS_PER_GPU} hardware.num_workers.eval=${EVAL_WORKERS_PER_GPU}

```

**Comment by NikolaZubic** [comment]
@XavierZXY As far as I remember, I had around 2.33 iterations per second for Gen1 dataset on A100 GPU. It could depend also on your CPU, Disk I/O and the GPUs itself.
