### ISSUE TITLE
S5 pytorch license

### ISSUE THREAD

**Issue by i404788** [uzh-rpg/ssms_event_cameras#7]
Hey there,

I'm the author of s5-pytorch, and noticed you used added the code to the project. I'm happy it's been of use to you, but I would appreciate it if the license for that directory was indicated as having original license (MPL-2.0) it had, or a link to the original source so license can be found there.

Thanks in advance

**Comment by NikolaZubic** [comment]
Dear @i404788 , I have added the source to README.md.

**Comment by i404788** [comment]
@NikolaZubic Thank you for the quick response, that's fine by me
