### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by JiakangYuan** [uzh-rpg/ssms_event_cameras#9]
Hello, I am unable to download the dataset from your server right now. Could you please check if it is a server issue? Thanks!

**Comment by WaterCube001** [comment]
Same issue about the dataset, both China and Singapore cannot access to the link. Please check the download method. Thank you!

**Comment by WaterCube001** [comment]
It works! Thanks a lot! :)

**Comment by WaterCube001** [comment]
A correct data process instruction link is here: https://github.com/uzh-rpg/ssms_event_cameras/blob/master/RVT/scripts/genx/README.md

**Comment by NikolaZubic** [comment]
@JiakangYuan Does it now work for you? I checked now and don't see any issues.
